"""Add footer settings to site_settings

Revision ID: 2024_add_footer_settings
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2024_add_footer_settings'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('site_description', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('site_settings', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('site_settings', sa.Column('contact_address', sa.String(length=500), nullable=True))
    op.add_column('site_settings', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('site_settings', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    op.add_column('site_settings', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('site_settings', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('site_settings', sa.Column('privacy_policy', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('terms_conditions', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('refund_policy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'refund_policy')
    op.drop_column('site_settings', 'terms_conditions')
    op.drop_column('site_settings', 'privacy_policy')
    op.drop_column('site_settings', 'twitter_url')
    op.drop_column('site_settings', 'instagram_url')
    op.drop_column('site_settings', 'youtube_url')
    op.drop_column('site_settings', 'facebook_url')
    op.drop_column('site_settings', 'contact_address')
    op.drop_column('site_settings', 'contact_email')
    op.drop_column('site_settings', 'contact_phone')
    op.drop_column('site_settings', 'site_description')
    # ### end Alembic commands ###
